version: '3'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
    - mysql:/var/lib/mysql
    - ../db/:/docker-entrypoint-initdb.d
    ports:
    - "3306:3306"

volumes:
  mysql:
