info:
  contact: {}
  description: LabLibrary backend API reference.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: LabLibrary API
  version: "1.0"
paths: {}
swagger: "2.0"
